spring:
  profiles.active: test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.DerbyDialect
  datasource:
    name: demo
    url: jdbc:derby:/db/contact_db;create=true
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    continue-on-error: true
logging:
  config: classpath:logback.xml
---
spring:
  profiles: local
  redis:
    host: localhost
    port: 6379
server:
  port : 8099
---
spring:
  profiles: test
  redis:
      host: localhost
      port: 6379
server:
  port : 8099


