spring:
  profiles.active: test
logging:
  config: classpath:logback.xml
---
spring:
  profiles: local
  redis:
    host: localhost
    port: 6379
server:
  port : 8099
---
spring:
  profiles: test
  redis:
      host: localhost
      port: 6379
server:
  port : 8099


